### ISSUE TITLE
 No rule to make target 'arch/arm64/boot/dts/qcom/sdm845-v2.dtb'

### ISSUE THREAD

**Issue by sanlic** [YumeMichi/kernel_xiaomi_sdm845#1]
make[3]: *** No rule to make target 'arch/arm64/boot/dts/qcom/sdm845-v2.dtb', needed by 'arch/arm64/boot/dts/qcom/beryllium-p0-v2-overlay.dtbo'。 停止。
../scripts/Makefile.build:653: recipe for target 'arch/arm64/boot/dts/qcom' failed
make[2]: *** [arch/arm64/boot/dts/qcom] Error 2
arch/arm64/Makefile:161: recipe for target 'dtbs' failed
make[1]: *** [dtbs] Error 2
make[1]: Leaving directory '/data/mix3/kernel_xiaomi_sdm845/out'
Makefile:152: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by YumeMichi** [comment]
which branch?
